name: Deploy to EC2

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: 3.110.124.247
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PHRASE }}
          script: |
            cd /home/ubuntu/bms-ci-next-app
            git stash
            git pull
            chmod +x deploy.sh
            ./deploy.sh

