name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 43.204.107.45
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.PHRASE }}
          port: 22
          script: |
            cd /home/ubuntu/bms-ci-next-app
            git pull
            /home/ubuntu/.nvm/versions/node/v22.17.1/bin/pnpm install
            /home/ubuntu/.nvm/versions/node/v22.17.1/bin/pnpm run build
            /home/ubuntu/.nvm/versions/node/v22.17.1/bin/pm2 restart fe-server
            /home/ubuntu/.nvm/versions/node/v22.17.1/bin/pm2 restart http-server
            /home/ubuntu/.nvm/versions/node/v22.17.1/bin/pm2 restart ws-server
            echo "Deployment completed! App is running with PM2."